### ISSUE TITLE
tf macro should be named TF instead

### ISSUE THREAD

**Issue by femtotrader** [femtotrader/TimeFrames.jl#40]
Hello,

I don't know if it's a good practice for Julia code but I think 
`tf` macro should be named `TF` instead.

It have been added by @iblis17 
 in https://github.com/femtotrader/TimeFrames.jl/commit/378b7963fcabbf37cfa84535a1f8fc2c6045fc7c

So it should be possible to do:

```julia
tf = TF"4H"
```

Your opinion?

**Comment by iblislin** [comment]
I prefer it in lowercase.
And I usually do this:
```julia
julia> tf = tf"1M"
TimeFrames.MonthEnd(1 month, End::TimeFrames.Boundary = 2)
```

**Comment by femtotrader** [comment]
I noticed that it's possible but that's odd.

I just keep this issue open some days / month to get some other opinions

**Comment by iblislin** [comment]
hmm, I think it's just like people usually does
```julia
ip = ip"1.2.3.4"
...
ip = ip"2.3.4.5"
...
```

**Comment by femtotrader** [comment]
ok so let's close
